In [29]:
import numpy as np
import matplotlib.pyplot as plt
import copy

In [30]:
import open3d as o3d

In [31]:
path = "C:/Users/schiavaz/lava-nc/depth/"
dataset = "data/esim_data/line_top/"

In [32]:
from os import listdir
fs = [f for f in listdir(path + dataset + "test/")]
pcds = [o3d.io.read_point_cloud(path + dataset + "test/"+ f) for f in fs]

In [33]:
pcd = o3d.io.read_point_cloud(path + dataset + "/test/2.336294000.pcd")
print(pcd)

PointCloud with 3742 points.


In [34]:
o3d.visualization.draw_geometries([pcd])

In [35]:
pcd_res = o3d.io.read_point_cloud(path + dataset + "/result_pcd.pcd")

In [36]:
o3d.visualization.draw_geometries([pcd_res, pcd])

In [37]:
def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp],
                                      zoom=0.4459,
                                      front=[0.9288, -0.2951, -0.2242],
                                      lookat=[1.6784, 2.0612, 1.4451],
                                      up=[-0.3402, -0.9189, -0.1996])

In [73]:
source = pcd_res
target = pcd
threshold = 100.0

T = np.eye(4)
T[:3, :3] = source.get_rotation_matrix_from_xyz((np.pi, 0, 0))
T[2, 3] = 0
trans_init = T
draw_registration_result(source, target, trans_init)

In [74]:
print("Apply point-to-point ICP")
reg_p2p = o3d.pipelines.registration.registration_icp(
    source, target, threshold, trans_init,
    o3d.pipelines.registration.TransformationEstimationPointToPoint())
print(reg_p2p)
print("Transformation is:")
print(reg_p2p.transformation)
draw_registration_result(source, target, reg_p2p.transformation)

Apply point-to-point ICP
RegistrationResult with fitness=1.000000e+00, inlier_rmse=8.029091e-02, and correspondence_set size of 27819
Access transformation to get result.
Transformation is:
[[ 9.99810524e-01 -4.42447988e-04  1.94607255e-02 -1.15972959e-01]
 [-2.85963569e-04 -9.99967613e-01 -8.04308516e-03 -3.58429800e-01]
 [ 1.94636539e-02  8.03599614e-03 -9.99778270e-01  8.46457573e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [72]:
8.029091e-02

0.08029091